-- MySQL Script generated by MySQL Workbench
-- 05/27/15 05:53:03
-- Model: New Model    Version: 1.0
-- MySQmovieIdL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies` ;

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `movies` ;

-- -----------------------------------------------------
-- Table `movies`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`Movie` ;

CREATE TABLE IF NOT EXISTS `movies`.`Movie` (
  `movieId` INT NOT NULL AUTO_INCREMENT,
  `movieName` VARCHAR(60) NOT NULL,
  `movieType` VARCHAR(25) NOT NULL,
  `movieLenght` SMALLINT NOT NULL,
  `movieYearRelease` DATE NOT NULL,
  `movieDesciption` TEXT NULL,
  `movieImage` VARCHAR(100) NULL,
  PRIMARY KEY (`movieId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
